# Generated by Django 3.1.3 on 2021-03-01 10:49

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_father', models.CharField(max_length=100)),
                ('dob', models.DateField(validators=[students.models.MinAgeValidator(18)])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('class_opted', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('marks', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
